#pragma once
#define PI 3.1415

#define NETWORK_SIZE 3
#define NETWORK_OUTPUT_SIZE 5
#define NETWORK_INPUT_SIZE 4

#define DIDIER_INPUT 2
#define DIDIER_OUTPUT EQUIPE_SIZE

const int LAYER_CONFIG[] = {NETWORK_INPUT_SIZE, 15, 25, NETWORK_OUTPUT_SIZE};

#define GAME_RESOLUTION 1

#define MAP_LENGTH 2000
#define MAP_HEIGHT 1000
#define GOAL_HEIGHT 25

#define PLAYER_MASS 100
#define PLAYER_SIZE 100
#define PLAYER_ACCELERATION 1

#define BALL_MASS 100
#define BALL_SIZE 100

#define EQUIPE_SIZE 3
